# Generated by Django 4.2.30 on 2026-08-10 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='demo_video',
            field=models.FileField(blank=True, null=True, upload_to='mentor_videos/'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='demo_video_url',
            field=models.URLField(blank=True, help_text='Alternative video link (e.g., YouTube/Loom/Drive)'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mentors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('chat_abuse', 'Harassment / Abusive Chat'), ('inappropriate_behavior', 'Inappropriate Behavior'), ('scam_fraud', 'Scam / Financial Fraud'), ('no_show', 'No-Show / Unresponsive'), ('policy_violation', 'Platform Terms Violation'), ('other', 'Other Issue')], default='chat_abuse', max_length=40)),
                ('description', models.TextField(help_text='Detailed description of the issue or chat violation')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved (Action Taken)'), ('dismissed', 'Dismissed (No Violation)')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes by admin after analyzing chat')),
                ('action_taken', models.CharField(blank=True, help_text='e.g. Account Suspended, Warning Issued, Dismissed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('chat_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='chat.chatroom')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
