# Generated by Django 4.2.30 on 2026-08-10 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mentorprofile_applied_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
