# Generated by Django on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_mentorprofile_applied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=1499.0, help_text='1-Month Mentorship (4 Sessions + Chat)', max_digits=8),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='quarterly_rate',
            field=models.DecimalField(decimal_places=2, default=3999.0, help_text='3-Month Mentorship (12 Sessions + Projects + Mock Interviews)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=499.0, max_digits=8),
        ),
    ]
