# Generated by Django 4.2.30 on 2026-08-10 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mentorprofile_monthly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('warning', 'Official Admin Warning'), ('suspension', 'Account Suspended'), ('approval', 'Mentor Approved'), ('rejection', 'Mentor Application Update'), ('session_request', 'Session Request'), ('session_accepted', 'Session Accepted'), ('session_rejected', 'Session Rejected'), ('review', 'New Review'), ('info', 'General Notification')], default='info', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
